disabled_rules:
 - line_length
 - trailing_whitespace
opt_in_rules:
 - unneeded_parentheses_in_closure_argument
# - trailing_closure
file_length:
  warning: 500
cyclomatic_complexity:
  warning: 10
  error: 25
